### ISSUE TITLE
How to pass environment variables?

### ISSUE THREAD

**Issue by dusansusic** [GoogleCloudPlatform/appengine-custom-runtimes-samples#16]
If running Docker container requires environment variables, how to pass that envs with `gcloud app deploy` command? Passing that env_vars inside app.yaml
```
env_variables:
  env1: value1
  env2: value2
  env3: value3
```

will not be picked by docker container.
